"""employer_status nullable = True

Revision ID: 19dbec0a68fa
Revises: a76260551d89
Create Date: 2024-01-12 14:51:30.788661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dbec0a68fa'
down_revision = 'a76260551d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employer_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employer_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
