"""employer_status return

Revision ID: 1e2513e567ca
Revises: 19dbec0a68fa
Create Date: 2024-01-12 14:56:59.436969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2513e567ca'
down_revision = '19dbec0a68fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employer_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('employer_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
