"""Job status nullable = True

Revision ID: 323a834948bb
Revises: 1e2513e567ca
Create Date: 2024-01-12 14:57:51.126442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323a834948bb'
down_revision = '1e2513e567ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
