"""Добавление поля image_filename

Revision ID: 38dd54de9e5d
Revises: a9c9666bac83
Create Date: 2023-12-13 12:25:29.834598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dd54de9e5d'
down_revision = 'a9c9666bac83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
