"""attachmentJob2

Revision ID: 454a5bd99756
Revises: cd22b939c880
Create Date: 2024-01-17 12:31:23.447760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454a5bd99756'
down_revision = 'cd22b939c880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resume', ['resume_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resume_id')

    # ### end Alembic commands ###
