"""job_resume_association

Revision ID: 624916afc921
Revises: 465a87709dc1
Create Date: 2024-01-17 12:51:02.921743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624916afc921'
down_revision = '465a87709dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_resume_association',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], )
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('fk_job_resume_id', type_='foreignkey')
        batch_op.drop_column('resume_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_job_resume_id', 'resume', ['resume_id'], ['id'])

    op.drop_table('job_resume_association')
    # ### end Alembic commands ###
