"""Добавление поля image_filename

Revision ID: a9c9666bac83
Revises: a677b43bb1fe
Create Date: 2023-12-13 03:22:27.927267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c9666bac83'
down_revision = 'a677b43bb1fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
